Account page 2
svrphoenix/project-group3fe pull request #48
Opened 2023-08-18 18:51 UTC by IrynaBondarenko7

2023-08-18 19:28 UTC, svrphoenix requested changes

2023-08-18 19:28 UTC, svrphoenix commented on src/api/authServices.js
> +  accessToken.set(data.token);
accessToken.set(data.token);
це не потрібно бо апдейт юзера токен не змінює

2023-08-18 19:28 UTC, svrphoenix commented on src/components/UserForm/FileUploadComponent.jsx
export const FileUploadComponent = ({ handleFiles, fileListRef }) => {
експорт треба замінити на дефолтний
export default FileUploadComponent

2023-08-18 19:28 UTC, svrphoenix commented on src/components/UserForm/Icons.jsx
тут краще теж зробити export {ChevronDownIcon, AddIcon} у кінці. Це я усіх просив. Ну поки що в різнобій. Заодно підчисть консоль-логи та закоментований код

2023-08-18 19:28 UTC, svrphoenix commented on src/redux/auth/operations.js
помилку поверни так 
catch ({ response: { status, data } }) {
      return thunkAPI.rejectWithValue({
        status,
        message: data.message,
      });
    }

2023-08-18 21:34 UTC, IrynaBondarenko7 commented on src/api/authServices.js
> +  accessToken.set(data.token);
прибрала

2023-08-18 21:34 UTC, IrynaBondarenko7 commented on src/components/UserForm/FileUploadComponent.jsx
виправила

2023-08-18 21:35 UTC, IrynaBondarenko7 commented on src/components/UserForm/Icons.jsx
зробила

2023-08-18 21:38 UTC, IrynaBondarenko7 commented on src/redux/auth/operations.js
переробила

2023-08-19 15:52 UTC, svrphoenix approved these changes

2023-08-19 15:52 UTC, merged